#!/usr/bin/env sh

set -e

STAC_FASTAPI_COLLECTIONS_HREF=data/collections.json \
STAC_FASTAPI_LANDING_ID="${STAC_FASTAPI_LANDING_ID:-stac-fastapi-geoparquet}" \
STAC_FASTAPI_TITLE="${STAC_FASTAPI_TITLE:-stac-fastapi-geoparquet}" \
STAC_FASTAPI_DESCRIPTION="${STAC_FASTAPI_DESCRIPTION:-A stac-fastapi implementation with a stac-geoparquet backend}" \
    uv run fastapi dev src/stac_fastapi/geoparquet/main.py
